version: "3"
services:
  web:
    restart: always
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
  db:
    image: postgres:11.0-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
