# Generated by Django 2.1.5 on 2020-03-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rebel', '0002_auto_20190114_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='has_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='has_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='has_complained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='has_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='has_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='has_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='has_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='has_stored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='has_unsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
