# Generated by Django 3.2 on 2021-04-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rebel', '0005_auto_20200314_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
